// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eCommerce.Api.Dal;

#nullable disable

namespace eCommerce.Api.Migrations
{
    [DbContext(typeof(eCommerceApiDbContext))]
    [Migration("20260627185438_SeedCatalogData")]
    partial class SeedCatalogData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("eCommerce.Api.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.HasKey("CartId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("eCommerce.Api.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("eCommerce.Api.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Sports Shoes",
                            Description = "Performance footwear built for running, training and the field."
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Casual Shoes",
                            Description = "Everyday comfort and style for any occasion."
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Boots",
                            Description = "Rugged, durable boots made for the outdoors."
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Lifestyle",
                            Description = "Trend-forward sneakers to complete your look."
                        });
                });

            modelBuilder.Entity("eCommerce.Api.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("eCommerce.Api.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("InvoiceId");

                    b.HasIndex("CartId")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("eCommerce.Api.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MadeIn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("int");

                    b.Property<string>("ReturnPolicy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WarrantyPeriod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            BrandId = 1,
                            CategoryId = 1,
                            Description = "Lightweight cushioned running shoe for men.",
                            Discount = 15,
                            Gender = "Men",
                            MadeIn = "India",
                            Picture = "~/Images/adidas_soc_m_1.jpeg",
                            ProductName = "Adidas Galaxy Runner",
                            ProductQuantity = 1,
                            ReturnPolicy = "15-Days",
                            UnitPrice = 5999.00m,
                            WarrantyPeriod = "1-Year"
                        },
                        new
                        {
                            ProductId = 2,
                            BrandId = 1,
                            CategoryId = 1,
                            Description = "Breathable everyday trainer for women.",
                            Discount = 10,
                            Gender = "Women",
                            MadeIn = "India",
                            Picture = "~/Images/adidas_soc_w_1.jpeg",
                            ProductName = "Adidas Cloudfoam (W)",
                            ProductQuantity = 1,
                            ReturnPolicy = "15-Days",
                            UnitPrice = 5499.00m,
                            WarrantyPeriod = "1-Year"
                        },
                        new
                        {
                            ProductId = 3,
                            BrandId = 1,
                            CategoryId = 1,
                            Description = "Responsive boost cushioning for long runs.",
                            Discount = 20,
                            Gender = "Women",
                            MadeIn = "India",
                            Picture = "~/Images/adidas_soc_w_2.jpeg",
                            ProductName = "Adidas Pure Boost (W)",
                            ProductQuantity = 1,
                            ReturnPolicy = "15-Days",
                            UnitPrice = 7999.00m,
                            WarrantyPeriod = "1-Year"
                        },
                        new
                        {
                            ProductId = 4,
                            BrandId = 2,
                            CategoryId = 1,
                            Description = "Springy Zoom Air unit for explosive pace.",
                            Discount = 18,
                            Gender = "Men",
                            MadeIn = "India",
                            Picture = "~/Images/nike_soc_m_1.jpeg",
                            ProductName = "Nike Air Zoom",
                            ProductQuantity = 1,
                            ReturnPolicy = "15-Days",
                            UnitPrice = 8999.00m,
                            WarrantyPeriod = "1-Year"
                        },
                        new
                        {
                            ProductId = 5,
                            BrandId = 2,
                            CategoryId = 1,
                            Description = "Soft foam midsole for daily training.",
                            Discount = 12,
                            Gender = "Women",
                            MadeIn = "India",
                            Picture = "~/Images/nike_soc_w_1.jpeg",
                            ProductName = "Nike Revolution (W)",
                            ProductQuantity = 1,
                            ReturnPolicy = "15-Days",
                            UnitPrice = 6499.00m,
                            WarrantyPeriod = "1-Year"
                        },
                        new
                        {
                            ProductId = 6,
                            BrandId = 3,
                            CategoryId = 1,
                            Description = "Energy-return running shoe for men.",
                            Discount = 25,
                            Gender = "Men",
                            MadeIn = "India",
                            Picture = "~/Images/puma_soc_m_1.jpeg",
                            ProductName = "Puma Velocity",
                            ProductQuantity = 1,
                            ReturnPolicy = "15-Days",
                            UnitPrice = 5799.00m,
                            WarrantyPeriod = "1-Year"
                        },
                        new
                        {
                            ProductId = 7,
                            BrandId = 3,
                            CategoryId = 1,
                            Description = "Premium nitrogen-infused racing foam.",
                            Discount = 22,
                            Gender = "Men",
                            MadeIn = "India",
                            Picture = "~/Images/puma_soc_m_2.png",
                            ProductName = "Puma Nitro Pro",
                            ProductQuantity = 1,
                            ReturnPolicy = "15-Days",
                            UnitPrice = 9499.00m,
                            WarrantyPeriod = "1-Year"
                        },
                        new
                        {
                            ProductId = 8,
                            BrandId = 4,
                            CategoryId = 1,
                            Description = "Plush, lightweight ride for women.",
                            Discount = 14,
                            Gender = "Women",
                            MadeIn = "India",
                            Picture = "~/Images/reebook_soc_w1.jpeg",
                            ProductName = "Reebok Floatride (W)",
                            ProductQuantity = 1,
                            ReturnPolicy = "15-Days",
                            UnitPrice = 6999.00m,
                            WarrantyPeriod = "1-Year"
                        },
                        new
                        {
                            ProductId = 9,
                            BrandId = 5,
                            CategoryId = 2,
                            Description = "All-day casual comfort for men.",
                            Discount = 10,
                            Gender = "Men",
                            MadeIn = "India",
                            Picture = "~/Images/bata_c_m_1.jpeg",
                            ProductName = "Bata Comfort Walk",
                            ProductQuantity = 1,
                            ReturnPolicy = "15-Days",
                            UnitPrice = 2499.00m,
                            WarrantyPeriod = "1-Year"
                        },
                        new
                        {
                            ProductId = 10,
                            BrandId = 5,
                            CategoryId = 2,
                            Description = "Easy slip-on casual shoe.",
                            Discount = 5,
                            Gender = "Men",
                            MadeIn = "India",
                            Picture = "~/Images/bata_c_m_2.jpeg",
                            ProductName = "Bata Slip-On",
                            ProductQuantity = 1,
                            ReturnPolicy = "15-Days",
                            UnitPrice = 1999.00m,
                            WarrantyPeriod = "1-Year"
                        },
                        new
                        {
                            ProductId = 11,
                            BrandId = 5,
                            CategoryId = 2,
                            Description = "Lightweight casual shoe for women.",
                            Discount = 8,
                            Gender = "Women",
                            MadeIn = "India",
                            Picture = "~/Images/bata_c_w_1.jpeg",
                            ProductName = "Bata Breeze (W)",
                            ProductQuantity = 1,
                            ReturnPolicy = "15-Days",
                            UnitPrice = 2299.00m,
                            WarrantyPeriod = "1-Year"
                        },
                        new
                        {
                            ProductId = 12,
                            BrandId = 6,
                            CategoryId = 2,
                            Description = "Sporty casual look for men.",
                            Discount = 12,
                            Gender = "Men",
                            MadeIn = "India",
                            Picture = "~/Images/campus_c_m_1.jpeg",
                            ProductName = "Campus Street",
                            ProductQuantity = 1,
                            ReturnPolicy = "15-Days",
                            UnitPrice = 1799.00m,
                            WarrantyPeriod = "1-Year"
                        },
                        new
                        {
                            ProductId = 13,
                            BrandId = 6,
                            CategoryId = 2,
                            Description = "Fashion-forward casual for women.",
                            Discount = 15,
                            Gender = "Women",
                            MadeIn = "India",
                            Picture = "~/Images/campus_c_w_2.jpeg",
                            ProductName = "Campus Bloom (W)",
                            ProductQuantity = 1,
                            ReturnPolicy = "15-Days",
                            UnitPrice = 1899.00m,
                            WarrantyPeriod = "1-Year"
                        },
                        new
                        {
                            ProductId = 14,
                            BrandId = 7,
                            CategoryId = 2,
                            Description = "Comfortable casual everyday shoe.",
                            Discount = 10,
                            Gender = "Women",
                            MadeIn = "India",
                            Picture = "~/Images/sparx_c_w_1.jpeg",
                            ProductName = "Sparx Active (W)",
                            ProductQuantity = 1,
                            ReturnPolicy = "15-Days",
                            UnitPrice = 1599.00m,
                            WarrantyPeriod = "1-Year"
                        },
                        new
                        {
                            ProductId = 15,
                            BrandId = 3,
                            CategoryId = 2,
                            Description = "Clean court-style casual sneaker.",
                            Discount = 18,
                            Gender = "Men",
                            MadeIn = "India",
                            Picture = "~/Images/puma_c_m_1.jpg",
                            ProductName = "Puma Casual Court",
                            ProductQuantity = 1,
                            ReturnPolicy = "15-Days",
                            UnitPrice = 3499.00m,
                            WarrantyPeriod = "1-Year"
                        },
                        new
                        {
                            ProductId = 16,
                            BrandId = 8,
                            CategoryId = 3,
                            Description = "Rugged leather boots for tough terrain.",
                            Discount = 12,
                            Gender = "Men",
                            MadeIn = "India",
                            Picture = "~/Images/woodland_b_m_1.jpeg",
                            ProductName = "Woodland Trekker",
                            ProductQuantity = 1,
                            ReturnPolicy = "15-Days",
                            UnitPrice = 4999.00m,
                            WarrantyPeriod = "1-Year"
                        },
                        new
                        {
                            ProductId = 17,
                            BrandId = 8,
                            CategoryId = 3,
                            Description = "Durable hiking boots with grip sole.",
                            Discount = 16,
                            Gender = "Men",
                            MadeIn = "India",
                            Picture = "~/Images/woodland_b_m_2.jpg",
                            ProductName = "Woodland Summit",
                            ProductQuantity = 1,
                            ReturnPolicy = "15-Days",
                            UnitPrice = 5499.00m,
                            WarrantyPeriod = "1-Year"
                        },
                        new
                        {
                            ProductId = 18,
                            BrandId = 8,
                            CategoryId = 3,
                            Description = "Outdoor ankle boots for women.",
                            Discount = 10,
                            Gender = "Women",
                            MadeIn = "India",
                            Picture = "~/Images/woodland_b_w_1.jpg",
                            ProductName = "Woodland Trail (W)",
                            ProductQuantity = 1,
                            ReturnPolicy = "15-Days",
                            UnitPrice = 4799.00m,
                            WarrantyPeriod = "1-Year"
                        },
                        new
                        {
                            ProductId = 19,
                            BrandId = 5,
                            CategoryId = 3,
                            Description = "Sturdy everyday work boots.",
                            Discount = 8,
                            Gender = "Men",
                            MadeIn = "India",
                            Picture = "~/Images/bata_b_m_1.jpg",
                            ProductName = "Bata Ranger",
                            ProductQuantity = 1,
                            ReturnPolicy = "15-Days",
                            UnitPrice = 3299.00m,
                            WarrantyPeriod = "1-Year"
                        },
                        new
                        {
                            ProductId = 20,
                            BrandId = 6,
                            CategoryId = 3,
                            Description = "Lightweight hiking boots for men.",
                            Discount = 14,
                            Gender = "Men",
                            MadeIn = "India",
                            Picture = "~/Images/campus_b_m_1.jpg",
                            ProductName = "Campus Hiker",
                            ProductQuantity = 1,
                            ReturnPolicy = "15-Days",
                            UnitPrice = 2999.00m,
                            WarrantyPeriod = "1-Year"
                        },
                        new
                        {
                            ProductId = 21,
                            BrandId = 2,
                            CategoryId = 4,
                            Description = "Iconic everyday lifestyle sneaker.",
                            Discount = 20,
                            Gender = "Men",
                            MadeIn = "India",
                            Picture = "~/Images/nike_l_m_1.jpg",
                            ProductName = "Nike Lifestyle Low",
                            ProductQuantity = 1,
                            ReturnPolicy = "15-Days",
                            UnitPrice = 7499.00m,
                            WarrantyPeriod = "1-Year"
                        },
                        new
                        {
                            ProductId = 22,
                            BrandId = 2,
                            CategoryId = 4,
                            Description = "Retro court styling for daily wear.",
                            Discount = 15,
                            Gender = "Men",
                            MadeIn = "India",
                            Picture = "~/Images/nike_l_m_2.jpg",
                            ProductName = "Nike Retro Court",
                            ProductQuantity = 1,
                            ReturnPolicy = "15-Days",
                            UnitPrice = 6999.00m,
                            WarrantyPeriod = "1-Year"
                        },
                        new
                        {
                            ProductId = 23,
                            BrandId = 2,
                            CategoryId = 4,
                            Description = "Streetwear-ready sneaker for women.",
                            Discount = 18,
                            Gender = "Women",
                            MadeIn = "India",
                            Picture = "~/Images/nike_l_w_1.jpg",
                            ProductName = "Nike Street (W)",
                            ProductQuantity = 1,
                            ReturnPolicy = "15-Days",
                            UnitPrice = 7299.00m,
                            WarrantyPeriod = "1-Year"
                        },
                        new
                        {
                            ProductId = 24,
                            BrandId = 6,
                            CategoryId = 4,
                            Description = "Modern lifestyle sneaker for men.",
                            Discount = 12,
                            Gender = "Men",
                            MadeIn = "India",
                            Picture = "~/Images/campus_l_m_2.jpg",
                            ProductName = "Campus Urban",
                            ProductQuantity = 1,
                            ReturnPolicy = "15-Days",
                            UnitPrice = 2199.00m,
                            WarrantyPeriod = "1-Year"
                        },
                        new
                        {
                            ProductId = 25,
                            BrandId = 3,
                            CategoryId = 4,
                            Description = "Stylish everyday sneaker for women.",
                            Discount = 22,
                            Gender = "Women",
                            MadeIn = "India",
                            Picture = "~/Images/puma_l_w_1.jpg",
                            ProductName = "Puma Lifestyle (W)",
                            ProductQuantity = 1,
                            ReturnPolicy = "15-Days",
                            UnitPrice = 3999.00m,
                            WarrantyPeriod = "1-Year"
                        });
                });

            modelBuilder.Entity("eCommerce.Api.Models.Shipper", b =>
                {
                    b.Property<int>("ShipperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ShipperId");

                    b.ToTable("Shippers");

                    b.HasData(
                        new
                        {
                            ShipperId = 1,
                            ContactNumber = "1800-233-1234",
                            EmailId = "support@bluedart.com",
                            Name = "BlueDart Express"
                        },
                        new
                        {
                            ShipperId = 2,
                            ContactNumber = "1800-209-3666",
                            EmailId = "care@delhivery.com",
                            Name = "Delhivery"
                        },
                        new
                        {
                            ShipperId = 3,
                            ContactNumber = "1860-123-4567",
                            EmailId = "help@dtdc.com",
                            Name = "DTDC Couriers"
                        },
                        new
                        {
                            ShipperId = 4,
                            ContactNumber = "9098987665",
                            EmailId = "sk@gmail.com",
                            Name = "Fedex"
                        });
                });

            modelBuilder.Entity("eCommerce.Api.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierId = 1,
                            City = "Bengaluru",
                            Name = "Adidas India Pvt Ltd"
                        },
                        new
                        {
                            SupplierId = 2,
                            City = "Mumbai",
                            Name = "Nike Sports Trading"
                        },
                        new
                        {
                            SupplierId = 3,
                            City = "Kolkata",
                            Name = "Bata India Ltd"
                        },
                        new
                        {
                            SupplierId = 4,
                            City = "New Delhi",
                            Name = "Campus Activewear"
                        },
                        new
                        {
                            SupplierId = 5,
                            City = "Pune",
                            Name = "New Balance"
                        });
                });

            modelBuilder.Entity("eCommerce.Api.Models.Cart", b =>
                {
                    b.HasOne("eCommerce.Api.Models.Customer", "Customer")
                        .WithMany("Carts")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("eCommerce.Api.Models.CartItem", b =>
                {
                    b.HasOne("eCommerce.Api.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eCommerce.Api.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eCommerce.Api.Models.Invoice", b =>
                {
                    b.HasOne("eCommerce.Api.Models.Cart", "Cart")
                        .WithOne("Invoice")
                        .HasForeignKey("eCommerce.Api.Models.Invoice", "CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("eCommerce.Api.Models.Product", b =>
                {
                    b.HasOne("eCommerce.Api.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("eCommerce.Api.Models.Cart", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("eCommerce.Api.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("eCommerce.Api.Models.Customer", b =>
                {
                    b.Navigation("Carts");
                });
#pragma warning restore 612, 618
        }
    }
}
